<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class InventoryItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get the first admin user for added_by
        $adminUser = DB::table('users')->where('role', 'ADMIN')->first();
        
        if (!$adminUser) {
            $this->command->warn('No admin user found. Please create an admin user first.');
            return;
        }

        $now = Carbon::now();

        $inventoryItems = [
            // Camera Equipment
            [
                'name' => 'Sony A7 III Camera Body',
                'code' => 'CAM-001',
                'description' => 'Professional full-frame mirrorless camera with 24.2MP sensor',
                'category' => 'Camera Equipment',
                'quantity' => 5,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 1999.99,
                'location' => 'Studio Room A - Equipment Shelf 1',
                'condition' => 'good',
                'last_maintenance_date' => $now->copy()->subMonths(1),
                'next_maintenance_date' => $now->copy()->addMonths(5),
                'is_active' => true,
                'notes' => 'Regular maintenance required every 6 months',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Canon EF 24-70mm f/2.8L II Lens',
                'code' => 'LENS-001',
                'description' => 'Professional standard zoom lens with constant f/2.8 aperture',
                'category' => 'Camera Equipment',
                'quantity' => 8,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 1899.00,
                'location' => 'Studio Room A - Equipment Shelf 2',
                'condition' => 'good',
                'last_maintenance_date' => $now->copy()->subMonths(2),
                'next_maintenance_date' => $now->copy()->addMonths(4),
                'is_active' => true,
                'notes' => 'Clean lens regularly and check for dust',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'DJI Ronin-S Gimbal',
                'code' => 'GIM-001',
                'description' => '3-axis handheld gimbal stabilizer for DSLR cameras',
                'category' => 'Stabilization',
                'quantity' => 3,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 699.00,
                'location' => 'Studio Room B - Storage Cabinet',
                'condition' => 'good',
                'last_maintenance_date' => $now->copy()->subWeeks(3),
                'next_maintenance_date' => $now->copy()->addMonths(3),
                'is_active' => true,
                'notes' => 'Battery lasts approximately 12 hours',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Lighting Equipment
            [
                'name' => 'Aputure 120D Mark II LED Light',
                'code' => 'LIGHT-001',
                'description' => '180W daylight LED light with wireless control',
                'category' => 'Lighting',
                'quantity' => 10,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 795.00,
                'location' => 'Studio Room C - Lighting Rack 1',
                'condition' => 'good',
                'last_maintenance_date' => $now->copy()->subMonths(1),
                'next_maintenance_date' => $now->copy()->addMonths(5),
                'is_active' => true,
                'notes' => 'Includes barn doors and softbox diffuser',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Godox SL-60W LED Video Light',
                'code' => 'LIGHT-002',
                'description' => 'Compact 60W continuous LED light with Bowens mount',
                'category' => 'Lighting',
                'quantity' => 15,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 119.00,
                'location' => 'Studio Room C - Lighting Rack 2',
                'condition' => 'good',
                'last_maintenance_date' => $now->copy()->subMonths(2),
                'next_maintenance_date' => $now->copy()->addMonths(4),
                'is_active' => true,
                'notes' => 'Quiet cooling fan for video production',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'C-Stand with Boom Arm',
                'code' => 'STAND-001',
                'description' => 'Heavy-duty light stand with grip head and boom arm',
                'category' => 'Lighting',
                'quantity' => 20,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 145.00,
                'location' => 'Studio Room C - Stand Storage',
                'condition' => 'good',
                'last_maintenance_date' => null,
                'next_maintenance_date' => null,
                'is_active' => true,
                'notes' => 'Check knuckles and tightening mechanisms regularly',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Audio Equipment
            [
                'name' => 'Rode NTG3 Shotgun Microphone',
                'code' => 'AUDIO-001',
                'description' => 'Professional RF-bias shotgun microphone for video production',
                'category' => 'Audio',
                'quantity' => 6,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 699.00,
                'location' => 'Studio Room D - Audio Cabinet',
                'condition' => 'good',
                'last_maintenance_date' => $now->copy()->subMonths(3),
                'next_maintenance_date' => $now->copy()->addMonths(3),
                'is_active' => true,
                'notes' => 'Includes shock mount and windscreen',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Zoom H6 Audio Recorder',
                'code' => 'AUDIO-002',
                'description' => '6-track portable audio recorder with interchangeable mic capsules',
                'category' => 'Audio',
                'quantity' => 4,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 399.00,
                'location' => 'Studio Room D - Audio Cabinet',
                'condition' => 'good',
                'last_maintenance_date' => $now->copy()->subWeeks(2),
                'next_maintenance_date' => $now->copy()->addMonths(4),
                'is_active' => true,
                'notes' => 'Uses 4x AA batteries or AC adapter',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sennheiser EW 112P G4 Wireless Lavalier',
                'code' => 'AUDIO-003',
                'description' => 'Camera-mount wireless microphone system with omni lavalier',
                'category' => 'Audio',
                'quantity' => 8,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 599.00,
                'location' => 'Studio Room D - Audio Cabinet',
                'condition' => 'good',
                'last_maintenance_date' => $now->copy()->subMonth(),
                'next_maintenance_date' => $now->copy()->addMonths(5),
                'is_active' => true,
                'notes' => 'Check battery levels before each shoot',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Grip Equipment
            [
                'name' => 'Apple Box Set (Full, Half, Quarter, Pancake)',
                'code' => 'GRIP-001',
                'description' => 'Wooden apple boxes in various sizes for grip work',
                'category' => 'Grip',
                'quantity' => 12,
                'reserved_quantity' => 0,
                'unit' => 'set',
                'unit_cost' => 89.00,
                'location' => 'Main Storage - Grip Section',
                'condition' => 'good',
                'last_maintenance_date' => null,
                'next_maintenance_date' => null,
                'is_active' => true,
                'notes' => 'Essential for height adjustments and leveling',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Matthews Doorway Dolly',
                'code' => 'GRIP-002',
                'description' => 'Compact camera dolly with adjustable track width',
                'category' => 'Grip',
                'quantity' => 2,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 1295.00,
                'location' => 'Main Storage - Grip Section',
                'condition' => 'fair',
                'last_maintenance_date' => $now->copy()->subMonths(4),
                'next_maintenance_date' => $now->copy()->addMonths(2),
                'is_active' => true,
                'notes' => 'Wheels need lubrication every 3 months',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Sand Bags (25 lbs)',
                'code' => 'GRIP-003',
                'description' => 'Heavy-duty sand bags for weighting stands and equipment',
                'category' => 'Grip',
                'quantity' => 30,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 15.00,
                'location' => 'Main Storage - Grip Section',
                'condition' => 'good',
                'last_maintenance_date' => null,
                'next_maintenance_date' => null,
                'is_active' => true,
                'notes' => 'Always use when extending stands to full height',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Backdrop & Sets
            [
                'name' => 'Seamless Paper Backdrop (2.72m x 11m)',
                'code' => 'BACK-001',
                'description' => 'Professional seamless paper in various colors',
                'category' => 'Backdrops',
                'quantity' => 25,
                'reserved_quantity' => 0,
                'unit' => 'roll',
                'unit_cost' => 45.00,
                'location' => 'Studio Room A - Backdrop Storage',
                'condition' => 'good',
                'last_maintenance_date' => null,
                'next_maintenance_date' => null,
                'is_active' => true,
                'notes' => 'Stock includes: White (10), Black (5), Gray (5), Misc colors (5)',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Green Screen Backdrop (3m x 6m)',
                'code' => 'BACK-002',
                'description' => 'Collapsible chroma key green screen for video production',
                'category' => 'Backdrops',
                'quantity' => 4,
                'reserved_quantity' => 0,
                'unit' => 'piece',
                'unit_cost' => 299.00,
                'location' => 'Studio Room B - Backdrop Storage',
                'condition' => 'good',
                'last_maintenance_date' => null,
                'next_maintenance_date' => null,
                'is_active' => true,
                'notes' => 'Keep wrinkle-free for best keying results',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Consumables
            [
                'name' => 'Gaffer Tape (2" x 50 yards)',
                'code' => 'CONS-001',
                'description' => 'Professional matte black gaffer tape',
                'category' => 'Consumables',
                'quantity' => 50,
                'reserved_quantity' => 0,
                'unit' => 'roll',
                'unit_cost' => 18.00,
                'location' => 'Main Storage - Consumables Shelf',
                'condition' => 'good',
                'last_maintenance_date' => null,
                'next_maintenance_date' => null,
                'is_active' => true,
                'notes' => 'Reorder when stock drops below 20 rolls',
                'added_by' => $adminUser->id,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('inventory_items')->insert($inventoryItems);

        $this->command->info('Successfully seeded ' . count($inventoryItems) . ' inventory items!');
    }
}
